<a href="https://colab.research.google.com/github/Jihyun13579/ESAA/blob/main/1009(%EC%9B%94)_%EA%B3%BC%EC%A0%9C_%ED%85%8D%EC%8A%A4%ED%8A%B8%EB%B6%84%EC%84%9D_%EB%8D%B0%EC%9D%B4%EC%BD%98_%ED%95%84%EC%82%AC_%EC%8A%A4%ED%84%B0%EB%94%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1009(월) 과제_텍스트분석_데이콘 필사 스터디
### 2129014 박지현

### 실습 링크:
1) https://dacon.io/competitions/official/235670/codeshare/1840?page=undefined&dtype=recent&ptype=undefined

​

2) https://dacon.io/competitions/official/235670/codeshare/1823?page=2&dtype=recent

​

1. 형태소 분석(Stemming)

- 1-3. Mecab()은 오류 문제가 있어 제외하고 코드를 작성해주시면 됩니다.

​

3) https://dacon.io/competitions/official/235670/codeshare/1841?page=2&dtype=recent

## Facebook의 fasttext를 이용한 text classification
링크 : https://dacon.io/competitions/official/235670/codeshare/1840?page=undefined&dtype=recent&ptype=undefined

In [1]:
!pip install fasttext

1. 필요한 패키지 다운로드 후, 데이터 읽어오기
- 데이터 파일을 열어, text 파일을 author-text별로 쌍을 묶음

In [2]:
import fasttext

import pandas as pd
import numpy as np

train = pd.read_csv('/content/train.csv')

file = open('fasttexttrain.txt','w+')
for i in train.index:
    line = '__label__' + str(train['author'][i])+' '+train['text'][i]
    file.write(line+"\n")

2. 모델 생성 후 학습하기
 - 디폴트로 돌릴 시, 0.56
 - 최적화된 코드로 돌릴 시, 0.36

In [3]:
text_clf_model = fasttext.train_supervised('fasttexttrain.txt')  # 빠른 학습을 위해 이 코드 사용
# 아래는 하이퍼 파라미터를 조정한 코드로, 더 정확한 결과를 도출 가능하다.
# text_clf_model = fasttext.train_supervised('fasttexttrain.txt', epoch=30, minCount=2, maxn=10, verbose=0)
print(text_clf_model.words)
print(text_clf_model.labels)

['the', 'and', 'to', 'of', '</s>', 'a', 'I', 'in', 'was', 'that', 'he', 'his', 'you', 'with', 'had', 'it', 'odin', 'for', 'as', 'at', 'not', 'my', 'have', 'is', 'be', 'her', 'said', 'on', 'she', 'but', 'odin,', 'all', 'from', 'me', 'by', 'him', 'were', 'which', 'so', 'this', 'been', 'would', 'The', 'an', 'your', 'are', 'very', 'no', 'He', 'one', 'Mr.', 'could', 'what', 'we', 'they', 'will', 'if', 'or', 'upon', 'there', 'when', 'out', 'do', 'who', 'up', '“I', 'some', 'am', 'odin.', 'more', 'into', 'It', 'their', 'about', 'But', 'only', 'should', 'little', 'must', 'than', 'like', 'any', 'know', 'such', 'did', 'man', 'has', 'see', 'And', 'them', 'can', 'our', 'never', 'much', 'come', 'before', 'She', 'down', 'may', 'think', 'how', 'made', 'it,', 'time', 'me,', 'came', 'now', 'great', 'two', 'good', 'might', 'old', 'You', 'over', 'shall', 'after', 'own', 'cried', 'though', 'him,', 'go', 'it.', 'say', 'without', 'even', 'other', 'you,', 'looked', 'Mrs.', 'then', 'Miss', 'thought', 'every', 

3. 생성된 모델로 예시 text 예측해보기

In [4]:
reuslt = text_clf_model.predict("He was almost choking. There was so much, so much he wanted to say, but strange exclamations were all that came from his lips. The Pole gazed fixedly at him, at the bundle of notes in his hand; looked at odin, and was in evident perplexity.", k=5)
print(reuslt)

(('__label__3', '__label__2', '__label__0', '__label__1', '__label__4'), array([9.93905842e-01, 2.39557261e-03, 1.82576349e-03, 1.41904899e-03,
       5.03745396e-04]))


4. text 파일과 제출 파일 읽어오기

In [5]:
test = pd.read_csv('/content/test_x.csv')
submission = pd.read_csv('/content/sample_submission.csv', index_col=False)

5. test 데이터에 대해 예측 수행해보기
 - 각 클래스일 확률을 구하고, 제출 파일에 저장하기

In [6]:
for i in test.index:
    lable, proba = text_clf_model.predict(test['text'][i], k=5)
    for la, pr in zip(lable, proba):
        if '__label__0' == la:
            submission.loc[i, '0'] = pr
        elif '__label__1' == la:
            submission.loc[i, '1'] = pr
        elif '__label__2' == la:
            submission.loc[i, '2'] = pr
        elif '__label__3' == la:
            submission.loc[i, '3'] = pr
        elif '__label__4' == la:
            submission.loc[i, '4'] = pr
    # submission.loc[i, '0'] = proba[lable.loc('__label__0')]
    # submission.loc[i, '1'] = proba[4]
    # submission.loc[i, '2'] = proba[2]
    # submission.loc[i, '3'] = proba[0]
    # submission.loc[i, '4'] = proba[3]

submission.to_csv('result5_fasttext.csv', index=False)
print('end')

end


## [NLP 언제까지 미룰래? 일단 들어와!!] #2. NLP 전처리
링크 : https://dacon.io/competitions/official/235670/codeshare/1823?page=2&dtype=recent

### 형태소 분석 (Stemming)
: 단어나 문장의 언어적 속성을 파악하는 것, 보통 품사의 태깅을 통해 이루어짐
- 한국어 형태소 분석 :Konlpy 패키지에 있는 다양한 함수 이용
- 목적 : 주로 형태소 단위로 의미있는 단어를 가져가고 싶거나, 품사 태깅을 통해 형용사나 명사를 추출하고 싶을 때 많이 이용
- 모델링보다 성능에 더 중요한 영향 미칠 수도 있는 중요한 과정!

#### 1-1. Kkma()

In [7]:
!pip install konlpy

In [8]:
from konlpy.tag import Kkma
kkma = Kkma()

sentence = '데이콘에서 다양한 컴피티션을 즐기면서 실력있는 데이터 분석가로 성장하세요!!.'

print("형태소 단위로 문장 분리")
print("----------------------")
print(kkma.morphs(sentence))
print(" ")
print("문장에서 명사 추출")
print("----------------------")
print(kkma.nouns(sentence))
print(" ")
print("품사 태킹(PoS)")
print("----------------------")
print(kkma.pos(sentence))

형태소 단위로 문장 분리
----------------------
['데이', '콘', '에서', '다양', '하', 'ㄴ', '컴피티션', '을', '즐기', '면서', '실력', '있', '는', '데이터', '분석가', '로', '성장', '하', '세요', '!!', '.']
 
문장에서 명사 추출
----------------------
['데이', '데이콘', '콘', '다양', '컴피티션', '실력', '데이터', '분석가', '성장']
 
품사 태킹(PoS)
----------------------
[('데이', 'NNG'), ('콘', 'NNG'), ('에서', 'JKM'), ('다양', 'NNG'), ('하', 'XSV'), ('ㄴ', 'ETD'), ('컴피티션', 'UN'), ('을', 'JKO'), ('즐기', 'VV'), ('면서', 'ECE'), ('실력', 'NNG'), ('있', 'VV'), ('는', 'ETD'), ('데이터', 'NNG'), ('분석가', 'NNG'), ('로', 'JKM'), ('성장', 'NNG'), ('하', 'XSV'), ('세요', 'EFN'), ('!!', 'SW'), ('.', 'SF')]


#### 1-2. Okt()

In [9]:
from konlpy.tag import Okt
Okt = Okt()

sentence = '데이콘에서 다양한 컴피티션을 즐기면서 실력있는 데이터 분석가로 성장하세요!!.'

print("형태소 단위로 문장 분리")
print("----------------------")
print(Okt.morphs(sentence))
print(" ")
print("문장에서 명사 추출")
print("----------------------")
print(Okt.nouns(sentence))
print(" ")
print("품사 태킹(PoS)")
print("----------------------")
print(Okt.pos(sentence))

형태소 단위로 문장 분리
----------------------
['데', '이콘', '에서', '다양한', '컴피티션', '을', '즐기면서', '실력', '있는', '데이터', '분석', '가로', '성장하세요', '!!.']
 
문장에서 명사 추출
----------------------
['데', '이콘', '컴피티션', '실력', '데이터', '분석', '가로']
 
품사 태킹(PoS)
----------------------
[('데', 'Noun'), ('이콘', 'Noun'), ('에서', 'Josa'), ('다양한', 'Adjective'), ('컴피티션', 'Noun'), ('을', 'Josa'), ('즐기면서', 'Verb'), ('실력', 'Noun'), ('있는', 'Adjective'), ('데이터', 'Noun'), ('분석', 'Noun'), ('가로', 'Noun'), ('성장하세요', 'Adjective'), ('!!.', 'Punctuation')]


#### 1-3. Mecab () < 오류 있어 제외!

### 2. 표제어 추출(Lemmatization)
- stemming과 비슷하게, 단어의 본 모습을 찾아주는 과정
- 단, Lemmatization이 더 정확도가 높은 것으로 보임

In [10]:
from konlpy.tag import Kkma
kkma = Kkma()

sentence = '성장했었다.'

print("품사 태킹(PoS)")
print("----------------------")
print(kkma.pos(sentence))

품사 태킹(PoS)
----------------------
[('성장', 'NNG'), ('하', 'XSV'), ('었', 'EPT'), ('었', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


In [11]:
sentence = '성장하였었다.'

print("품사 태킹(PoS)")
print("----------------------")
print(kkma.pos(sentence))

품사 태킹(PoS)
----------------------
[('성장', 'NNG'), ('하', 'XSV'), ('였', 'EPT'), ('었', 'EPT'), ('다', 'EFN'), ('.', 'SF')]


### 3. 불용어 제거(Stopwords removing)
- 불용서 : 문장에서 큰 의미가 없다고 생각되는 단어, 글자들

- 예시 코드
 1. 영어 소문자와 한글을 제외한 모든 문자를 제거
 2. Okt를 이용해 형태소 분석
 3. 형태소 분석기를 거쳐 나온 결과들 중 stopwords 리스트에 포함되지 않는 토큰만 token이라는 리스트에 반환

In [12]:
import re
from konlpy.tag import Okt

tokenizer = Okt()
def text_preprocessing(text,tokenizer):

    stopwords = ['을', '를', '이', '가', '은', '는']

    txt = re.sub('[^가-힣a-z]', ' ', text)
    token = tokenizer.morphs(txt)
    token = [t for t in token if t not in stopwords]

    return token

ex_text = "이번에 새롭게 개봉한 영화의 배우들은 모두 훌륭한 연기력과 아름다운 목소리를 갖고 있어!!"
example_pre= text_preprocessing(ex_text,tokenizer)

- 위의 코드의 결과 보기

In [13]:
print(example_pre)

['이번', '에', '새롭게', '개봉', '한', '영화', '의', '배우', '들', '모두', '훌륭한', '연기력', '과', '아름다운', '목소리', '갖고', '있어']


### 4. 대회 적용

In [14]:
train = pd.read_csv('/content/train.csv')
train.head()

index                                               text  author
0      0  He was almost choking. There was so much, so m...       3
1      1             “Your sister asked for it, I suppose?”       2
2      2   She was engaged one day as she walked, in per...       1
3      3  The captain was in the porch, keeping himself ...       4
4      4  “Have mercy, gentlemen!” odin flung up his han...       3

In [15]:
def text_preprocessing(text_list):

    stopwords = ['을', '를', '이', '가', '은', '는', 'null'] #불용어 설정
    tokenizer = Okt() #형태소 분석기
    token_list = []

    for text in text_list:
        txt = re.sub('[^가-힣a-z]', ' ', text) #한글과 영어 소문자만 남기고 다른 글자 모두 제거
        token = tokenizer.morphs(txt) #형태소 분석
        token = [t for t in token if t not in stopwords or type(t) != float] #형태소 분석 결과 중 stopwords에 해당하지 않는 것만 추출
        token_list.append(token)

    return token_list, tokenizer

#형태소 분석기를 따로 저장한 이유는 후에 test 데이터 전처리를 진행할 때 이용해야 되기 때문입니다.
train['new_article'], okt = text_preprocessing(train['text'])

## [NLP 언제까지 미룰래? 일단 들어와!!] #3. Vectorization
링크: https://dacon.io/competitions/official/235670/codeshare/1841?page=2&dtype=recent


: NLP를 컴퓨터가 이해할 수 있게 수치로 바꾸는 것
- 토큰들을 벡터화 하기 이전, 형태소 분석을 이용해 문장을 원하는 토큰들로 분리하는 것이 필요

In [16]:
from konlpy.tag import Okt
import re

Okt = Okt()

sentences = ['자연어 처리는 정말 정말 즐거워.', '즐거운 자연어 처리 다같이 해보자.']
tokens = []

for sentence in sentences:
    sentence = re.sub('[^가-힣a-z]', ' ', sentence) #간단한 전처리
    token = (Okt.morphs(sentence)) #형태소 분석기를 이용햔 토큰 나누기
    tokens.append(' '.join(token))

print("형태소 단위로 문장 분리")
print("----------------------")
print(tokens)

형태소 단위로 문장 분리
----------------------
['자연어 처리 는 정말 정말 즐거워', '즐거운 자연어 처리 다 같이 해보자']


### 1. One-Hot Encoding
: 해당 단어가 존재하면 1, 그렇지 않으면 0으로 표시되는 기법
- 단점 : vocabulary 크기가 커짐에 따라 많은 공간 차지, 벡터가 굉장히 sparse 해짐 > 모델에게 좋은 특성 알려주지 못하는 경우가 대부분임

In [17]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

t = Tokenizer()
t.fit_on_texts(tokens)
print("각 토큰에게 고유의 정수 부여")
print("----------------------")
print(t.word_index)
print(" ")

s1=t.texts_to_sequences(tokens)[0]
print("부여된 정수로 표시된 문장1")
print("----------------------")
print(s1)
print(" ")

s2=t.texts_to_sequences(tokens)[1]
print("부여된 정수로 표시된 문장2")
print("----------------------")
print(s2)
print(" ")

s1_one_hot = to_categorical(s1)
print("문장1의 one-hot-encoding")
print("----------------------")
print(s1_one_hot)
print(" ")

s2_one_hot = to_categorical(s2)
print("문장2의 one-hot-encoding")
print("----------------------")
print(s2_one_hot)

각 토큰에게 고유의 정수 부여
----------------------
{'자연어': 1, '처리': 2, '정말': 3, '는': 4, '즐거워': 5, '즐거운': 6, '다': 7, '같이': 8, '해보자': 9}
 
부여된 정수로 표시된 문장1
----------------------
[1, 2, 4, 3, 3, 5]
 
부여된 정수로 표시된 문장2
----------------------
[6, 1, 2, 7, 8, 9]
 
문장1의 one-hot-encoding
----------------------
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
 
문장2의 one-hot-encoding
----------------------
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### 2. Count vectorization
: vocabulary 활용하여 각 문장이 갖고 있는 토큰의 count를 기반으로 문장을 vectorization해줌
- 벡터화 결과 : 각 문장 > vocabulary의 인덱스 기준으로 카운트가 정수로 표시됨
- 단점 : sklearn의 CountVectorizer : 한 글자는 자동으로 제거해줌
- 형태소 분석의 중요성 : 같은 원본을 가지는 '즐거운', '즐거워' > okt의 구분하지 못함으로 다른 토큰으로 분리됨 > 모델에서 같은 의미의 토큰을 다르게 학습할 수 있다!

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(tokens) #여러 개의 문장을 넣어줘야 작동합니다!!

print(vectorizer.get_feature_names_out())
print(vectors.toarray())

['같이' '자연어' '정말' '즐거운' '즐거워' '처리' '해보자']
[[0 1 2 0 1 1 0]
 [1 1 0 1 0 1 1]]


### TfIdf
TfIdf의 핵심
1. 단어가 몇 번 등장했는지에 대한 정보
2. 어떤 단어가 언급된 문서의 수가 적다면, 그 단어는 문서를 분류하는 데 있어서 중요한 단어
> 즉, Tfldf : 등장 횟수도 많고, 문서 분별력 있는 단어들을 점수화하여 벡터화하는 기법

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(min_df=0)
tfidf_vectorizer = tfidf.fit_transform(tokens)

#tf-idf dictionary
tfidf_dict = tfidf.get_feature_names_out()
print(tfidf_dict)
print(tfidf_vectorizer.toarray())

['같이' '자연어' '정말' '즐거운' '즐거워' '처리' '해보자']
[[0.         0.29017021 0.81564821 0.         0.4078241  0.29017021
  0.        ]
 [0.49922133 0.35520009 0.         0.49922133 0.         0.35520009
  0.49922133]]


### 4. Padding
- NLP에서는 row별(문장별) colum(토큰의 개수)가 같지 않아도 되는가? > 이전 사용하던 모델들: DataFrame 형식의 row별 동일한 colum수를 가짐, 그러나 지금처럼 가변 길이의 문장들을 입력으로 넣어도 되는가?
> NO! 기본적으로는 문장의 길이를 동일하게 맞춰주어야 한다!(가변 길이의 입력을 받는 모형들도 존재하긴 함...)
 - **Padding** : 문장의 길이를 맞춰주기 위해 부족한 길이만큼 문장의 뒤쪽에 0을 채워넣게 되는 과정

### 5. 대회 적용
- 특별한 vectorization 대신, keras의 texts_to_sequences를 통한 정수화만 진행해줄 것 > 그래도 높은 정확도

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

def text2sequence(train_text, max_len=100):

    tokenizer = Tokenizer() #keras의 vectorizing 함수 호출
    tokenizer.fit_on_texts(train_text) #train 문장에 fit
    train_X_seq = tokenizer.texts_to_sequences(train_text) #각 토큰들에 정수 부여
    vocab_size = len(tokenizer.word_index) + 1 #모델에 알려줄 vocabulary의 크기 계산
    print('vocab_size : ', vocab_size)
    X_train = pad_sequences(train_X_seq, maxlen = max_len) #설정한 문장의 최대 길이만큼 padding

    return X_train, vocab_size, tokenizer

train_X, vocab_size, vectorizer = text2sequence(train['text'], max_len = 100)

vocab_size :  42331


이후 과정 : Embedding 필요