<a href="https://colab.research.google.com/github/Jihyun13579/ESAA/blob/main/ESAA%EC%84%B8%EC%85%982_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [68]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)
print(np.show_config)

1.22.4
<function show at 0x7f687d9a0dc0>


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
array1 = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
print(array1.size * array1.itemsize)

8


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
array2 = np.zeros(10)
array2[4] = 1
array2

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
array3 = np.arange(10, 50)
array3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
np.sort(array3)[::-1] 

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
array4 = np.array([1,2,0,0,4,0])
np.nonzero(array4)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [34]:
from numpy.core.numeric import identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [39]:
np.random.random((3,3,3))

array([[[0.76928353, 0.36939643, 0.06082026],
        [0.49131584, 0.65878856, 0.23429982],
        [0.38799045, 0.74330751, 0.19195998]],

       [[0.22983349, 0.21722864, 0.66533354],
        [0.79948948, 0.38275389, 0.18418754],
        [0.52355228, 0.42659285, 0.9539567 ]],

       [[0.71549378, 0.1154091 , 0.57734333],
        [0.12469277, 0.29109939, 0.79648028],
        [0.69719711, 0.22287553, 0.43192992]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [88]:
np.random.random((10,10))
print(array5)
print(array5.min())
print(array5.max())

[[0.02327818 0.90120723 0.71577824 0.09165137 0.57291235 0.03556206
  0.3215685  0.89917935 0.40219445 0.79799137]
 [0.2065233  0.5459623  0.77216582 0.49088372 0.64373585 0.4581156
  0.719956   0.83560764 0.37446229 0.99579778]
 [0.12668951 0.50879454 0.07255558 0.05225111 0.01720971 0.31448214
  0.33441767 0.83166883 0.34959534 0.09257219]
 [0.91888375 0.67320678 0.39962404 0.38361894 0.38113338 0.03411294
  0.68691493 0.12104784 0.34951155 0.01907463]
 [0.29373449 0.0532131  0.25275452 0.09613233 0.78446969 0.70343822
  0.03709529 0.80689974 0.47414646 0.37761951]
 [0.77752143 0.02207859 0.43742777 0.22209326 0.62249553 0.17143563
  0.04629097 0.68970905 0.49895401 0.260401  ]
 [0.57559413 0.02700507 0.1698587  0.62481112 0.92081313 0.619592
  0.95062601 0.83641363 0.93891579 0.92111276]
 [0.20087848 0.25603438 0.82544008 0.96003786 0.16657472 0.49034971
  0.20927848 0.88238106 0.5739852  0.83495474]
 [0.8478632  0.72690034 0.51039004 0.02526454 0.51575613 0.01688568
  0.12997451 0.

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [48]:
array6 = np.random.random(30)
array6.mean()

0.5052701612982976

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [55]:
array2d = np.ones((5,5))
array2d[1:-1, 1:-1] = 0
array2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [61]:
nan
False
False
nan
True
False

NameError: ignored

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [76]:
np.diag((1,2,3,4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [81]:
array17 = np.ones((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            array17[i,j] = 0

array17

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [87]:
np.unravel_index(100, (6, 7, 8))

100

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [93]:
array19 = np.random.random((5,5))
( array19 - np.mean(array19) ) / np.std(array19)

array([[ 0.5204117 ,  1.35523608, -1.41871679,  0.01599304,  0.48455996],
       [ 0.02021975,  0.4345422 ,  1.26631613, -0.09345065,  1.03079912],
       [ 0.10878848, -1.92755585,  0.58740305, -2.01153058,  0.71824315],
       [ 0.91926825,  0.94232508, -1.12726985,  0.43275953,  0.68693173],
       [ 0.24860707, -1.81852422, -0.66457173,  0.48725918, -1.19804383]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [99]:
np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])

<ipython-input-99-c7cad8eaf91f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np.dtype([('r',np.ubyte,1),('g',np.ubyte,1),('b',np.ubyte,1),('a',np.ubyte,1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [103]:
A = np.arange(5*3).reshape(5,3)
B = np.arange(3*2).reshape(3,2)
np.dot(A, B)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [107]:
Z = np.arange(11)
Z[(3<Z) & (Z<8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [109]:
9    #0+1+2+3+4 = 10 에서 -1
10   #축이 -1 = 1차원에서 하라

10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [111]:
legal
legal
legal
legal
legal
illegal

(range(0, 5), -1)

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [124]:
nan
0
array([-9.22337204e+18])

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

array([-9.22337204e+18])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 32. Create a random vector of size 10 and sort it (★★☆)

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [ ]:
# column 2

In [ ]:
# column 3