<a href="https://colab.research.google.com/github/Jihyun13579/ESAA/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD_%EA%B0%80%EC%9D%B4%EB%93%9C_p_1_~_38_%ED%95%84%EC%82%AC_2023_03_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**파이썬 머신러닝 완벽 가이드 p. 1 ~ 38 필사**

2129014 박지현 

1. 머신러닝의 개념
- 일반적으로, '애플리게이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법' > 현재 기존 소프트웨어 코드에서 한계를 맞이했던 문제들을 머신러닝을 통해 해결하고 있음

- 업무적으로 복잡한 조건, 규칙들이 다양하게 결합, 시시각각으로 변화하여 관통하는 일정한 패턴 찻기 어려운 경우 > 머신러닝 사용 
ex. 금융거래 스팸메일 분류, 데이터마이닝, 영상 인식, 음성 인식, 자연어 처리

- 머신러닝: 데이터를 기반으로 숨겨진 패턴을 인지해 해결
머신러닝 알고리즘: 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법 적용을 통해 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출함
> 데이터 분석 영역에 새로운 혁신 ' 머신러닝 기반의 예측 분석' 가져옴



In [1]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

**3.넘파이**

Numerical Python (=NumPy, 넘파이) : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

- 루프를 사용하지 않고 대량 데이터의 배열 연산 가능하게 함 > 대량 데이터 기반의 과학/공학 프로그램, 파이썬 기반 패키지가 의존하고 있음

- C/C++ 등 저수준 언어 기반 호환 API 제공 > 수행성능이 좋은 C/C++ 등 타프로그램과 데이터 주고받거나 API 호출해 쉽게 통합할 수 있는 기능 제공

- 다양한 데이터 핸들링 기능 제공, but 판다스(파이쎤의 대표적인 데이터 처리 패키지)의 편리성에는 미치지 못함 >교재에서는 판다스의 데이터프레임을 주로 이용할 것임

- 넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요함! 
< 많은 머신러닝 알고리즘이 넘파이 기반 / 입력 데이터와 출력 데이터가 넘파이 배열 타입이기 때문 / 다른 데이터 핸들링 패키지 이해하는 데도 도움




**넘파이 ndarray 개요
1) 넘파이 모듈 임포트 (as np로 약어로 모듈 표현)**

-넘파이 기반 데이터 타입: ndarray > 넘파이에서 다차원 배열 쉽게 생성 & 다양한 연산 수행 가능

In [3]:
import numpy as np

**2) np.array() 함수 (넘파이)**

- 다양한 인자(파이썬의 리스트...) 입력받아서 ndarray로 변환하는 기능 수행

- array()함수의 인자: 주로 파이썬의 리스트 객체 
- [] 1차원 /  [[]] 2차원, 배열의 차원과 크기 쉽게 표현 가능
-ndarray: tolist() 메서드를 이용해 리스트 자료형으로 변환 가능

사용법: ndarray로 변환을 원하는 객체를 인자로 입력 > ndarray 반환


>생성된 ndarray 배열의 shape 변수: ndarray의 크기 = 행과 열의 수를 튜플 형태로 가지고 있음 > ndarray의 차원 알 수 있음 

- 사용법: ndarray.shape > 결과: ( , ) 의 튜플 형태
-1차원 데이터일 시, (데이터의 수, )
-2차원 데이터일 시, 행(로우)의 수, 열(칼럼)의 수) <로우와 칼럼으로 이루어짐

- ndarray의 차원과 크기를 튜플 형태로 나타냄

-명확히 차원이 차수를 요구하는 입출력, 변환의 경우 차원의 차수가 달라 오류 발생 빈번 > 차원의 차수를 변환하는 방법 : reshape()함수


In [6]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


>ndarray.ndim

: 각 array의 차원 확인 가능

In [8]:
#.format을 이용해 문자열 출력
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'
.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


**3) ndarray의 데이터타입**

- ndarray내 데이터값 : 숫자형(int형, unsigned int형, float형, complex 타입), 문자열 값, 불 값 등 모두 가은

> 연산 특성상 '같은 데이터 타입'만 가능 > dtype 속성으로 확인 가능
- 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경 시, 데이터 크기가 더 큰 데이터 타입으로 형 변환 일괄 적용
- ex. 한 개의 ndarray 객체에 int와 float 함께 있을 수 X


In [9]:
#리스트 자료형 list1의 값: integer 숫자 1,2,3
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [10]:
# int형 값과 문자열이 섞여있는 리스트
list2 = [1,2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)
#결과: 숫자형 값 1,2가 모두 문자열 값(=유니코드 문자열 값)으로 변환됨

#int형 값과 float형이 섞여 있는 리스트
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


> astype 메서드: ndarray 내 데이터값의 타입 변경 가능

- 사용법: astype(인자로 원하는 타입을 문자열로 지정)
- 대용량 데이터를 ndarray로 만들 때, 메모리를 절약해야 할 경우 보통 이용됨 >수행곡도 느려지거나 메모리 부족으로 오류 발생 방지

In [11]:
#int형 데이터를 float64형 데이터로 변환
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

#그 float64를 데이터를 int32형 데이터로 변환
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

#float를 int형으로 변경할 시, 소수점 이하는 모두 없어짐
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


**4)ndarray를 편리하게 생성하기-arange,zeros,ones**

- 특정 크기나 차원을가진 ndarray를 연속값 or 0 or 1로 초기화해 쉽게 생성해야 할 경우(ex.테스트용으로 데이터 생성, 대규모 데이터 일괄 초기화) 

: arange() / zeros(), ones()를 이용해 쉽게 ndarray 생성 가능

> arange()

- 파이썬 표준 함수 range()와 유사한 기능 = array를 range()로 표현하는 것

- '0'부터 '함수 인자 값 -1'까지의 값을 순차적으로 ndarray의 데이터값으로 변환
- 디폴트 함수 인자: stop 값 / start 값도 부여해 0이 아닌 다른 값부터 시작한 연속 값도 부여 가능

In [13]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)
#결과: 0부터 stop 값인 10에서 -1을 더한 값인 9까지의 연속 숫자 값으로 구성된 1차원 ndarray

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


> zeros()

- zeros(튜플 형태의 shape값) > 모든 값을 0으로 채운 해당 shape을 가진 ndarray 반환
- dtype 지정 X 시, default로 float64형의 데이터로 ndarray를 채움 > 옵션 변경 시: zeros(튜플 형태의 shape값, dtype = ' ')

> ones()

- ones(튜플 형태의 shape값) > 모든 값을 1으로 채운 해당 shape을 가진 ndarray 반환

- dtype 지정 X 시, default로 float64형의 데이터로 ndarray를 채움 > 옵션 변경 시: ones(튜플 형태의 shape값, dtype = ' ')

In [14]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.zeros((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


**5)ndarray의 차원과 크기를 변경하는 reshape()**

- reshape() 메서드: ndarray를 특정 차원 및 크기로 변환

- 사용법: reshape(변환을 원하는 크기)

- 지정된 사이즈로 변경이 불가능할 시, 오류 발생

ex. (10,) 데이터 > (4,3) Shape 형태로 변경 불가

In [17]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [18]:
array1.reshape(4,3)
#결과: 오류 발생!

ValueError: ignored

> reshape() 실전에서 효율적으로 사용하는 경우: 인자로 -1 적용하는 경우

- -1 인자로 사용 시 : 원래 ndarray와 호환되는 새로운 shape으로 변환해줌
- -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없음

In [20]:
#array1 : 0~9까지의 데이터를 가지고 있는 1차원 ndarray
array1 = np.arange(10)
print(array1)
#array2 : 로우 인자가 -1. 칼럼 인자가 5 
#array1과 호환될 수 있는 2차원 ndarray로 변환하되, 
#고정된 5개의 칼럼에 맞는 로우를 자동으로 생성해 변환하라. = 2*5
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
#array1과 호환될 수 있는 2차원 ndarray로 변환하되, 
#고정된 5개의 로우에 맞는 칼럼을을 자동으로 생성해 변환하라. = 5*2
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [21]:
array1 = np.arange(10)
array4 = array.reshape(-1,4)
#오류 발생! <10개의 1차원 데이터를 고정된 4개의 칼럼을 가진 로우로 변경 불가하기 때문

NameError: ignored

- -1인자: reshape(-1,1) 형태로 자주 사용됨

> reshape(-1,1)
- 원본 ndarray가 어떤 형태더라도 '2차원'이고, 여러 개의 로우를 가지되 반드시 '1개의 칼럼을 가진 ndarray'로 변환됨을 보장함
- 여러 개의 넘파이 ndarray를 stack, concat 등을 결합할 때 각각의 ndarray 형태 통일할 때 사용됨


In [23]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())
#ndarray: tolist() 메서드를 이용해 리스트 자료형으로 변환 가능

#reshape(-1.1)을 이용해 3차원을 2차원으로 변경하는 예제
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.shape)
print('array5 shape:', array5.shape)

#reshape(-1.1)을 이용해 1차원을 2차원으로 변경하는 예제
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 (8, 1)
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


**6)넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)**

인덱싱 : ndarray의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 함

> 1. 특정 데이터만 추출: 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환

> 2. 슬라이싱(Slicing) : 연속된 인덱스상의 ndarray를 추출하는 방식
- 사용법: '시작 인덱스:종료 인덱스' > 시작 인덱스~종료 인덱스-1 위치에 있는 데이터의 ndarray 반환
- ex. 1:5 > 1과 4까지에 해당하는 ndarray 반환환

> 3. 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환

> 4. 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray만 반환

- 단일 값 추출
> 방법: [ndarray 객체에 해당하는 위치의 인덱스 값]

In [25]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
# index는 0부터 시작하므로 array[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
# array1[2] : ndarray 내의 데이터값 (ndarray 타입 X)
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


> - 인덱스 -1 : 맨 뒤의 데이터값 의미
- 인덱스 -2 : 맨 뒤에서 두번째에 있는 데이터값

In [26]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


> - 단일 인덱스의 이용 방법 중 하나: ndarray 내의 데이터값 간단히 수정 가능

In [27]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


 - 다차원 ndarray에서 단일 값 추출
 > 방법: [로우 위치의 인덱스, 칼럼 위치의 인덱스]
 - axis 0 : 로우 방향 축
 - axis 1 : 칼럼 방향 축
 - (ndarray에서는 로우, 칼럼 형식으로 표현 X)
 - 인덱싱 : [axis 0=0, axis1=1] 이 맞음!!
 - 3차원 인덱싱 : [axis 0=0, axis1=1,axis2=2] (= 행(로우),열(칼럼),높이)
  - 축 기반의 연산에서 axis 생략 시, axis 0 = 행을 의미


In [28]:
# 앞의 예체 1차원 ndarray > 2차원의 3*3 ndarray로 변환
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
#array2d 객체: 3개의 로우(행)이 0,1,2의 인덱스로, 3개의 칼럼(열)이 0,1,2의 인덱스로 되어 있음

# [row, col] 이용해 2차원의 ndarray에서 데이터 추출
print('(row=, col=0) index 가리키는 값:', array2d[0,0]) #첫번째 로우, 첫번째 칼럼
print('(row=0, col=1) index 가리키는 값:', array2d[0,1]) #첫번째 로우, 두번째 칼럼
print('(row=1, col=0) index 가리키는 값:', array2d[1,0]) #두번째 로우, 첫번째 칼럼
print('(row=2, col=2) index 가리키는 값:', array2d[2,2]) #세번째 로우, 세번째 칼럼

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


- 슬라이싱
 - 데이터 세트: ndarray 타입

> 방법: [시작 인덱스:종료 인덱스] > 시작 인덱스 ~ 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환
 - 슬라이싱 기호 ':' 사이 시작, 종료 인덱스 생략 가능
  - ':' 기호 앞 시작 인덱스 생략 시, 맨 처음 인덱스 0으로 간주
  - ':' 기호 뒤 종료 인덱스 생략 시, 맨 마지막 인덱스로 간주
  ':' 기호 앞&뒤 시작&종료 인덱스 생략 시, 맨 처음&마지막 인덱스로 간주


In [32]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [33]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


- 
 - 2차원 ndarray : [로우 인덱스 지칭, 칼럼 인덱스 지칭] < 각 로우, 칼럼 인덱스 지칭하는 곳에 슬라이싱 혹은 단일 값 인덱스 적용 가능

In [35]:
array1d = np.arange(start=1,stop=10)
array2d = array1.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


- 
 - 2차원 ndarray에서 뒤에 오는 인덱스 없애면, 1차원 ndarray 반환
 - 3차원 ndarray에서 뒤에 오는 인덱스 없애면, 2차원 ndarray 반환

In [36]:
print(array2d[0])
#결과: 로우 축(axis 0)의 첫번째 로우 ndarray를 반환

print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


- 팬시 인덱싱(Fancy Indexing)
 - 데이터 세트: ndarray 타입
 - 리스트나 ndarray로 인덱스 집합 지정 시, 해당 위치의 인덱스에 해당하는 ndarray 반환하는 인덱싱 방식

In [38]:
array1d = np.arange(start=1,stop=10)
array2d = array1.reshape(3,3)

#로우 축: 팬시 인덱싱 [0,1], 칼럼 축: 단일 값 인덱싱 2
# > (row,col) 인덱스: (0,2), (1,2)로 적용됨 > [3,6] 반환
array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

# (row,col) 인덱스: ( (0,0),(0,1) ), ( (1,0),(1,1) )로 적용됨 > [[1,2],[4,5]] 반환
array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

# (row,col) 인덱스: ( (0,:),(1,:) )로 적용됨 > [[1,2,3],[4,5,6]] 반환
array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

array2d[[0,1],2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


- 불린 인덱싱(Boolean Indexing)
 - 데이터 세트: ndarray 타입
 - 조건 필터링과 검색 동시 가능 > 매우 자주 사용됨
 - for loop/if else 문보다 훨씬 간단하게 데이터에 조건을 걸어 그 조건에 맞는 데이터만 인덱싱 가능

 > 방법: ndarray의 인덱스를 지정하는 []내에 조건문을 그대로 기재
 - ndarray[원하는 필터링 조건]

In [39]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


> 어떻게 조건 필터링이 이루어져 이런 결과를 내는가?
- Step1: ndarray 에 조건식을 붙일 시, 그 조건식의 각각의 답인 False/True로 이뤄진 nadarray 객체 반환됨 
- Step2: 이 조건으로 반환된 ndarray 객체를 인덱싱 지정한느 [ ] 에 입력 시, False 값 무시, 'True 값이 있는 위치 인덱스 값' (True 값 자체인 1 저장 X)으로 자동 변환
- Step3: 변환되어 저장된  인덱스 위치의 데이터만 반환

In [40]:
array1d > 5
# 결과를 [ ]에 집어넣을 시: True 값인 인덱스 [5,6,7,8]이 만들어짐 
# > 이 위치 인덱스에 해당한느 데이터 세트 [6,7,8,9] 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [41]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)
# 결과: 위, 아래와 같음

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [42]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


**7)행렬의 정렬 - sort()와 argsort()**

넘파이의 행렬 정렬의 대표적인 방법: np.sort() & ndarray.sort()

정렬된 행렬의 인덱스 반환: argsort()

- 행렬 정렬

1) np.sort() : 원 행렬 그대로 유지한 채, 원 행렬의 정렬된 행렬 반환
> 사용법: np.sort(정렬하고자 하는 행렬)

2) ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환, 반환값 = None
> 사용법: 정렬하고자 하는 행렬.sort()

 - 둘 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬

In [43]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
# 결과: 원본 행렬 변경하지 않고 정렬된 형태로 반환

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:',sort_array2)
print('org_array.sort() 호출 후 원본 행렬:',org_array)
# 결과: 원본 행렬 자체를 정렬한 값으로 변환

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


 - 내림차순으로 정렬하려면? 
 : [::-1] 적용
 
 ex. np.sort()[::-1]

In [44]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


 - 행렬이 2차원 이상일 경우?
 : axis축 값 설정 통해 로우 방향, 칼럼 방향으로 정렬 수행 가능

In [46]:
array2d = np.array([[8,12],
                    [7,1 ]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스를 반환하기

> np.argsort() : 원본 행렬이 정렬되었을 때, 기존 원본 행렬 원소에 대한 인덱스 필요 시 사용
 - np.argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

In [47]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


 - 내림차순으로 정렬했다면?
 : [::-1] 적용
 
 ex. np.argsort()[::-1]

In [48]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(' 행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

 행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


 - 넘파이의 ndarray: 메타 데이터 가질 수 X > 실제 값과 그 값이 뜻한느 메타 데이터를 별도의 ndarray로 각각 가져야 함 

 ex. 학생 이름 / 시험 성적 > 각각의 ndarray

 - 이때, 어떤 하나의 오름차순/내림차순으로 다른 하나를 출력하고자 할 시, np.argsort(오름차순/내림차순의 기준에 되는 ndarray)에서 반환된 인덱스를 다른 하나에 팬시 인덱스로 적용해 추출 가능
  - 넘파이의 데이터 추출에서 많이 사용됨


In [49]:
import numpy as np

name_array = np.array(['john', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['john' 'Sarah' 'Samuel' 'Mike' 'Kate']


**8)행렬의 정렬 - sort()와 argsort()**

1) 행렬 내적(행렬 곱)

np.dot() : 두 행렬 A와 B의 내적 계산 가능

- 두 행렬 A와 B 내적 = 왼쪽 행렬의 로우(행)과 오른쪽 행렬의 칼럼(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값

- 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 계산 가능 

In [51]:
A = np.array( [[1,2,3],
               [4,5,6]] )
B = np.array( [[7,8],
               [9,10],
               [11,12]] )
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


2) 전치 행렬

np.transpose(행렬) : 그 행렬의 전치행렬

- 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬 ( = A^T)

In [52]:
A = np.array( [[1,2],
               [3,4]] )
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
